"""initial migration

Revision ID: 14253b97afe0
Revises: 
Create Date: 2020-07-01 18:27:22.514928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14253b97afe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_reporter_id'), 'quote', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_quote_timestamp'), 'quote', ['timestamp'], unique=False)
    op.create_index(op.f('ix_quote_user_id'), 'quote', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_user_id'), table_name='quote')
    op.drop_index(op.f('ix_quote_timestamp'), table_name='quote')
    op.drop_index(op.f('ix_quote_reporter_id'), table_name='quote')
    op.drop_table('quote')
    # ### end Alembic commands ###
