"""added an index to the server id too.... so really everything except for the body

Revision ID: ddfcd1fcd755
Revises: 14253b97afe0
Create Date: 2020-07-01 18:45:08.735315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfcd1fcd755'
down_revision = '14253b97afe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quote_server_id'), 'quote', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_server_id'), table_name='quote')
    # ### end Alembic commands ###
